CREATE DATABASE HIMS;

USE HIMS;

-- TABLE: Accessrights

CREATE TABLE AccessRights (
    AccessRightID BIGINT AUTO_INCREMENT PRIMARY KEY,
    UserID BIGINT NOT NULL,
    FunctionalityID BIGINT NOT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- select * from AccessRights;

show tables;
drop table Admission;
show tables;

CREATE TABLE Admission (
    AdmissionId BIGINT AUTO_INCREMENT PRIMARY KEY,
    PatientCategoryID INT NOT NULL,
    PatientId BIGINT NOT NULL,
    UnitId INT NOT NULL,
    DoctorId BIGINT NOT NULL,
    AdmissionDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    IPDNumber BIGINT NOT NULL,
    RelativeName VARCHAR(200) DEFAULT NULL,
    RelationId INT DEFAULT NULL,
    BedId INT NOT NULL,
    CompanyId INT NOT NULL,
    IsMLC BOOLEAN DEFAULT FALSE,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: Advance
CREATE TABLE Advance (
    AdvanceId BIGINT AUTO_INCREMENT PRIMARY KEY,
    PatientId BIGINT NOT NULL,
    AdvAmount DECIMAL(18, 2) DEFAULT NULL,
    Used DECIMAL(18, 2) DEFAULT NULL,
    Refund DECIMAL(18, 2) DEFAULT NULL,
    Balance DECIMAL(18, 2) DEFAULT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: ApplicationFunctionality
CREATE TABLE ApplicationFunctionality (
    FunctionalityID BIGINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Level INT NOT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: Bed
CREATE TABLE Bed (
    BedId INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    WardId INT DEFAULT NULL,
    RoomId INT DEFAULT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: Bill
CREATE TABLE Bill (
    BillId BIGINT AUTO_INCREMENT PRIMARY KEY,
    BillDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    VisitId BIGINT DEFAULT NULL,
    AdmissionId BIGINT DEFAULT NULL,
    TotalAmount DECIMAL(18, 2) DEFAULT NULL,
    AdvanceAmount DECIMAL(18, 2) DEFAULT NULL,
    Concession DECIMAL(18, 2) DEFAULT NULL,
    FinalBillAmount DECIMAL(18, 2) DEFAULT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: Charge
CREATE TABLE Charge (
    ChargeId BIGINT AUTO_INCREMENT PRIMARY KEY,
    VisitId BIGINT DEFAULT NULL,
    AdmissionId BIGINT DEFAULT NULL,
    ServiceId BIGINT NOT NULL,
    Rate DECIMAL(18, 2) NOT NULL,
    Quantity INT NOT NULL,
    Amount DECIMAL(18, 2) NOT NULL,
    Concession DECIMAL(18, 2) DEFAULT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: City
CREATE TABLE City (
    CityID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    StateID INT NOT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);


-- Table: Country
CREATE TABLE Country (
    CountryID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    NationalityID INT DEFAULT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: Department
CREATE TABLE Department (
    DepartmentID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    IsClinical BOOLEAN NOT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: Discharge
CREATE TABLE Discharge (
    DischargeId BIGINT AUTO_INCREMENT PRIMARY KEY,
    AdmissionId BIGINT NOT NULL,
    DoctorId BIGINT NOT NULL,
    DischargeDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    DischargeNotes VARCHAR(2000) DEFAULT NULL,
    FileAttachedPath VARCHAR(500) DEFAULT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: Doctor
CREATE TABLE Doctor (
    DoctorID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DepartmentID INT NOT NULL,
    FirstName VARCHAR(150) NOT NULL,
    MiddleName VARCHAR(150) DEFAULT NULL,
    LastName VARCHAR(150) NOT NULL,
    Qualification VARCHAR(150) DEFAULT NULL,
    GenderID INT DEFAULT NULL,
    DateOfBirth DATE DEFAULT NULL,
    ContactNo1 VARCHAR(15) DEFAULT NULL,
    ContactNo2 VARCHAR(15) DEFAULT NULL,
    Email VARCHAR(100) DEFAULT NULL,
    AddressLine1 VARCHAR(150) DEFAULT NULL,
    AddressLine2 VARCHAR(150) DEFAULT NULL,
    Pincode VARCHAR(10) DEFAULT NULL,
    CityID INT DEFAULT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);


-- Table: Gender
CREATE TABLE Gender (
    GenderID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: InsuranceCompany
CREATE TABLE InsuranceCompany (
    CompanyId INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: Nationality
CREATE TABLE Nationality (
    NationalityID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: Patient
CREATE TABLE Patient (
    PatientID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(150) NOT NULL,
    MiddleName VARCHAR(150) DEFAULT NULL,
    LastName VARCHAR(150) NOT NULL,
    GenderID INT NOT NULL,
    DateOfBirth DATE DEFAULT NULL,
    ContactNo1 VARCHAR(15) DEFAULT NULL,
    ContactNo2 VARCHAR(15) DEFAULT NULL,
    Email VARCHAR(100) DEFAULT NULL,
    AddressLine1 VARCHAR(150) DEFAULT NULL,
    AddressLine2 VARCHAR(150) DEFAULT NULL,
    Pincode VARCHAR(10) DEFAULT NULL,
    CityID INT DEFAULT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: PatientCategory
CREATE TABLE PatientCategory (
    PatientCategoryID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: Relation
CREATE TABLE Relation (
    RelationID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: Room
CREATE TABLE Room (
    RoomId INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    WardID INT NOT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);


show tables;
DROP TABLE service, servicecategory, servicetype, staff, state, unit, user;
show tables;


-- Table: Service
CREATE TABLE Service (
    ServiceId BIGINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(200) NOT NULL,
    ServiceCategoryId INT NOT NULL,
    Rate DECIMAL(18, 2) NOT NULL,
    ServiceTypeId INT NOT NULL,
    CompanyId INT DEFAULT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: ServiceCategory
CREATE TABLE ServiceCategory (
    ServiceCategoryId INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: ServiceType
CREATE TABLE ServiceType (
    ServiceTypeID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) DEFAULT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: Staff
CREATE TABLE Staff (
    StaffID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DepartmentID INT NOT NULL,
    FirstName VARCHAR(150) NOT NULL,
    MiddleName VARCHAR(150) DEFAULT NULL,
    LastName VARCHAR(150) NOT NULL,
    GenderID INT NOT NULL,
    DateOfBirth DATE DEFAULT NULL,
    ContactNo1 VARCHAR(15) DEFAULT NULL,
    ContactNo2 VARCHAR(15) DEFAULT NULL,
    Email VARCHAR(100) DEFAULT NULL,
    AddressLine1 VARCHAR(150) DEFAULT NULL,
    AddressLine2 VARCHAR(150) DEFAULT NULL,
    Pincode VARCHAR(10) DEFAULT NULL,
    CityID INT DEFAULT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: State
CREATE TABLE State (
    StateID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    CountryID INT DEFAULT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: Unit
CREATE TABLE Unit (
    UnitID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: User
CREATE TABLE User (
    UserID BIGINT AUTO_INCREMENT PRIMARY KEY,
    StaffID BIGINT NOT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: Visit
CREATE TABLE Visit (
    VisitId BIGINT AUTO_INCREMENT PRIMARY KEY,
    PatientCategoryID INT NOT NULL,
    PatientId BIGINT NOT NULL,
    DoctorID BIGINT NOT NULL,
    UnitId INT NOT NULL,
    VisitDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    OPDNumber BIGINT NOT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: Ward
CREATE TABLE Ward (
    WardID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    UnitId INT DEFAULT NULL,
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: Prescription
CREATE TABLE Prescription (
    PrescriptionId BIGINT AUTO_INCREMENT PRIMARY KEY,
    VisitId BIGINT NOT NULL,
    Path VARCHAR(500),
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Table: ClinicalNote
CREATE TABLE ClinicalNote (
    ClinicalNoteId BIGINT AUTO_INCREMENT PRIMARY KEY,
    AdmissionId BIGINT NOT NULL,
    Path VARCHAR(500),
    Status BOOLEAN DEFAULT TRUE,
    AddedBy INT DEFAULT NULL,
    AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedBy BIGINT DEFAULT NULL,
    UpdatedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

show tables;
